# Generated by Django 5.1.1 on 2024-09-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_students', models.IntegerField(default=0)),
                ('total_trainers', models.IntegerField(default=0)),
                ('active_courses', models.IntegerField(default=0)),
                ('attendance_rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
