# Generated by Django 5.1.1 on 2024-09-30 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigBlueButtonRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=100, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('wait_for_moderator', models.BooleanField(default=False)),
                ('recordable', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.studentcourse')),
            ],
        ),
        migrations.CreateModel(
            name='BigBlueButtonRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.CharField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('meta_data', models.JSONField(default=dict)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbb_integration.bigbluebuttonroom')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bigbluebuttonroom',
            constraint=models.UniqueConstraint(fields=('course',), name='unique_course_room'),
        ),
        migrations.AddConstraint(
            model_name='bigbluebuttonroom',
            constraint=models.UniqueConstraint(fields=('student_course',), name='unique_student_course_room'),
        ),
    ]
