# Generated by Django 5.1.1 on 2024-10-03 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_studentfeedbackhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=255, null=True)),
                ('audit_date', models.DateField(default=django.utils.timezone.now)),
                ('class_date', models.DateField(blank=True, null=True)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('grammar_theory_covered', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True)),
                ('vocabulary_covered', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True)),
                ('speaking_activity', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True)),
                ('feedback_shared', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True)),
                ('assessment_of_student', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('trainer_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_audits', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-audit_date'],
            },
        ),
    ]
