# Generated by Django 5.1.1 on 2024-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_traineraudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineraudit',
            name='class_on_portal',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='traineraudit',
            name='error_rectification_done',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='traineraudit',
            name='full_class_duration',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='traineraudit',
            name='login_on_time',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='traineraudit',
            name='session_on_time',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='traineraudit',
            name='study_material_shared',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='traineraudit',
            name='use_of_whiteboard',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='traineraudit',
            name='webcam_on',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=3, null=True),
        ),
    ]
